sudo: required

language: java

jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10

services:
  - docker

before_install:
- docker pull jboss/keycloak
- docker build -t vertx-test-keycloak vertx-auth-oauth2/src/test/fixtures
- docker run -d -p 8888:8080 vertx-test-keycloak
- docker ps -a

script:
- mvn verify -B -V
